import 'package:core/core.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/widgets.dart';

import 'app.dart';
import 'firebase_options.dart';
import 'features/notifications/presentation/fcm_route_resolver.dart';

/// Pending deep-link route from a push tap while the app was terminated.
/// Checked by [CustomerApp] after the router is created.
String? pendingPushRoute;

/// Background/terminated FCM message handler — must be a top-level function.
/// Runs in a separate isolate; no UI access available.
@pragma('vm:entry-point')
Future<void> _fcmBackgroundHandler(RemoteMessage message) async {
  debugPrint('[FCM] Background message: ${message.messageId}');
}

/// Shared startup used by every flavor entrypoint (main_dev/staging/prod).
Future<void> bootstrap(EnvConfig env) async {
  WidgetsFlutterBinding.ensureInitialized();
  EnvConfig.initialize(env);

  // Initialize Firebase — gracefully degraded when credentials are missing.
  // Until firebase_options.dart is generated by `flutterfire configure`,
  // DefaultFirebaseOptions throws UnsupportedError which we catch here.
  // Push stays disabled; IN_APP notifications are unaffected.
  await _initFirebase();

  runApp(await buildAppRoot(env: EnvConfig.current, child: const CustomerApp()));
}

Future<void> _initFirebase() async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    FirebaseMessaging.onBackgroundMessage(_fcmBackgroundHandler);

    // Capture initial message (app opened from terminated state via push tap).
    final initialMessage = await FirebaseMessaging.instance.getInitialMessage();
    if (initialMessage != null) {
      pendingPushRoute = resolveFcmRoute(initialMessage);
    }

    debugPrint('[Firebase] FCM initialized');
  } catch (e) {
    // Firebase credentials not configured yet — push is disabled.
    // See docs/mobile-firebase-setup.md to enable.
    debugPrint('[Firebase] FCM disabled: $e');
  }
}
