// TODO(Phase 5 / Firebase): Replace this stub with the real file generated by
// `flutterfire configure`. See docs/mobile-firebase-setup.md for instructions.
//
// Until replaced, Firebase.initializeApp() in bootstrap.dart catches the thrown
// UnsupportedError and continues with Firebase disabled (push = off, IN_APP ok).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Firebase push is not supported on this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzIyYCuL_Yr3LbuK4XLAlN1NCyUOXz1w',
    appId: '1:354414583922:android:875a26c80ae4b97a6ae2eb',
    messagingSenderId: '354414583922',
    projectId: 'real-estate-3054e',
    storageBucket: 'real-estate-3054e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16uNd3lL68YhxTBKnL8Y0FUsShgHSi2Y',
    appId: '1:354414583922:ios:46c0c76b348d62ae6ae2eb',
    messagingSenderId: '354414583922',
    projectId: 'real-estate-3054e',
    storageBucket: 'real-estate-3054e.firebasestorage.app',
    iosBundleId: 'com.realestate.customer.mobileCustomer',
  );
}
