/**
 * Shared styled-XLSX foundation (P15.2). One professional Arabic/RTL theme used
 * by every workbook export across the platform — table lists and board reports
 * alike — so the look stays consistent and the styling logic lives in one place.
 *
 * Pure `exceljs`; no chart/canvas dependency here (charts live in xlsx-chart.ts
 * so simple table exports never pull in the canvas binary). The CSV utility in
 * ./csv.ts is the untouched raw-data fallback.
 */
import { Workbook, type Cell, type Row, type Worksheet } from 'exceljs';

// ── Brand + palette (ARGB) ───────────────────────────────────────────────────
export const XLSX_BRAND = 'Devora';
export const XLSX_NAVY = 'FF1E3348'; // header fill / titles
export const XLSX_GOLD = 'FFC99A2E'; // accent
export const XLSX_GOLD_TINT = 'FFFBF3DE'; // totals row fill
export const XLSX_MUTED = 'FF64748B'; // secondary text
export const XLSX_ZEBRA = 'FFF8FAFC'; // alternating row fill
export const XLSX_CARD_BG = 'FFEEF2F7'; // KPI card fill (light slate)
export const XLSX_CARD_BORDER = 'FFCBD5E1'; // KPI card edge
export const XLSX_ALERT_BG = 'FFFBF3DE'; // alert/risk card fill (gold tint)

export const THIN_BORDER = {
  top: { style: 'thin' as const, color: { argb: 'FFE2E8F0' } },
  left: { style: 'thin' as const, color: { argb: 'FFE2E8F0' } },
  bottom: { style: 'thin' as const, color: { argb: 'FFE2E8F0' } },
  right: { style: 'thin' as const, color: { argb: 'FFE2E8F0' } },
};

function pad2(n: number): string {
  return String(n).padStart(2, '0');
}

/** Human-readable local timestamp for the "generated on" line. */
export function formatStamp(d: Date): string {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())} ${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}

/** A new workbook stamped with the brand as creator. */
export function createReportWorkbook(): Workbook {
  const wb = new Workbook();
  wb.creator = XLSX_BRAND;
  wb.created = new Date();
  return wb;
}

/** Navy fill + white bold — the shared table-header look. */
export function styleHeaderCell(cell: Cell): void {
  cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: XLSX_NAVY } };
  cell.alignment = { horizontal: 'center', vertical: 'middle' };
  cell.border = THIN_BORDER;
}

/** Bold gold-tinted totals row. */
export function styleTotalsRow(row: Row): void {
  row.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: XLSX_NAVY } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: XLSX_GOLD_TINT } };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
    cell.border = THIN_BORDER;
  });
}

/**
 * Merged navy title row (row 1) + a muted "generated on" stamp (row 2), spanning
 * `spanCols` columns. The caller owns column widths / frozen views.
 */
export function addReportTitle(ws: Worksheet, title: string, spanCols = 2): void {
  ws.mergeCells(1, 1, 1, spanCols);
  const t = ws.getCell(1, 1);
  t.value = title;
  t.font = { bold: true, size: 16, color: { argb: XLSX_NAVY } };
  t.alignment = { horizontal: 'right', vertical: 'middle' };
  ws.getRow(1).height = 26;

  ws.mergeCells(2, 1, 2, spanCols);
  const g = ws.getCell(2, 1);
  g.value = `تاريخ التوليد: ${formatStamp(new Date())}`;
  g.font = { italic: true, size: 10, color: { argb: XLSX_MUTED } };
  g.alignment = { horizontal: 'right' };
}

/** Standard footer line: "Generated by Devora". */
export function addFooter(ws: Worksheet): void {
  ws.addRow([]);
  const footer = ws.addRow([`Generated by ${XLSX_BRAND}`]);
  footer.getCell(1).font = { italic: true, size: 9, color: { argb: XLSX_MUTED } };
}

/**
 * Append a styled header row + data rows (borders + zebra striping) at the
 * worksheet's CURRENT position — no view/column reset, so it composes under a
 * title/filters block. Emits a merged "لا توجد بيانات" row when there is no data.
 */
export function appendTable(
  ws: Worksheet,
  headers: string[],
  rows: Array<Array<string | number | Date>>,
): void {
  const headerRow = ws.addRow(headers);
  headerRow.height = 22;
  headerRow.eachCell(styleHeaderCell);

  if (rows.length === 0) {
    const empty = ws.addRow(['لا توجد بيانات']);
    ws.mergeCells(empty.number, 1, empty.number, Math.max(1, headers.length));
    const c = empty.getCell(1);
    c.font = { italic: true, color: { argb: XLSX_MUTED } };
    c.alignment = { horizontal: 'center' };
    c.border = THIN_BORDER;
    return;
  }

  rows.forEach((r, idx) => {
    const row = ws.addRow(r);
    row.eachCell((cell) => {
      cell.border = THIN_BORDER;
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
      if (idx % 2 === 1) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: XLSX_ZEBRA } };
      }
    });
  });
}

/**
 * A clean RTL table that IS the sheet content: sets the RTL view, freezes the
 * header at row 1, applies column widths, then renders the table. Mutates the
 * sheet.
 */
export function addTable(
  ws: Worksheet,
  headers: string[],
  rows: Array<Array<string | number | Date>>,
  widths: number[],
): void {
  ws.views = [{ state: 'frozen', ySplit: 1, rightToLeft: true }];
  ws.columns = headers.map((_, i) => ({ width: widths[i] ?? 18 }));
  appendTable(ws, headers, rows);
}

/**
 * A titled RTL table sheet: navy title + generated-on stamp, an optional applied
 * "عوامل التصفية" line, then a frozen-header table. The default presentation for
 * the simple-list XLSX exports. Mutates the sheet.
 */
export function addTitledTable(
  ws: Worksheet,
  opts: {
    title: string;
    /** Applied filters as [label, value] pairs; omitted/empty → no filter line. */
    filters?: Array<[string, string]>;
    headers: string[];
    rows: Array<Array<string | number | Date>>;
    widths: number[];
  },
): void {
  const span = opts.headers.length;
  ws.columns = opts.widths.map((w) => ({ width: w }));
  addReportTitle(ws, opts.title, span);

  const applied = (opts.filters ?? []).filter(([, v]) => v !== '' && v != null);
  if (applied.length > 0) {
    const text = applied.map(([k, v]) => `${k}: ${v}`).join('  •  ');
    const fr = ws.addRow([`عوامل التصفية — ${text}`]);
    ws.mergeCells(fr.number, 1, fr.number, span);
    fr.getCell(1).font = { italic: true, size: 9, color: { argb: XLSX_MUTED } };
    fr.getCell(1).alignment = { horizontal: 'right' };
  }

  ws.addRow([]); // spacer
  const headerRowIndex = ws.rowCount + 1;
  ws.views = [{ state: 'frozen', ySplit: headerRowIndex, rightToLeft: true }];
  appendTable(ws, opts.headers, opts.rows);
}

// ── Board / proposal report helpers (P15.4) ──────────────────────────────────

/** A navy section-heading row with a full-width gold bottom rule. */
export function addSectionTitle(ws: Worksheet, text: string, span = 4): void {
  ws.addRow([]);
  const row = ws.addRow([text]);
  ws.mergeCells(row.number, 1, row.number, span);
  const goldRule = { bottom: { style: 'medium' as const, color: { argb: XLSX_GOLD } } };
  // Apply the underline across the whole span (a merged cell only renders the
  // border on its anchor otherwise).
  for (let c = 1; c <= span; c++) ws.getCell(row.number, c).border = goldRule;
  const c = row.getCell(1);
  c.value = text;
  c.font = { bold: true, size: 14, color: { argb: XLSX_NAVY } };
  c.alignment = { horizontal: 'right', vertical: 'middle' };
  row.height = 26;
}

// ── Polished board layout (P15.4.1) ──────────────────────────────────────────

/**
 * Prepare a board cover/overview sheet so it reads like a report, not a raw
 * grid: explicit column widths, RTL view with gridlines HIDDEN, and a
 * landscape fit-to-width page setup.
 */
export function setupBoardSheet(
  ws: Worksheet,
  opts: { widths: number[]; landscape?: boolean },
): void {
  ws.columns = opts.widths.map((w) => ({ width: w }));
  ws.views = [{ rightToLeft: true, showGridLines: false }];
  ws.pageSetup = {
    orientation: opts.landscape === false ? 'portrait' : 'landscape',
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    margins: { left: 0.4, right: 0.4, top: 0.5, bottom: 0.5, header: 0.3, footer: 0.3 },
  };
}

/**
 * A full-width navy banner (rows 1–3): gold brand line, large white report
 * title, and a muted generated-on stamp — the "this is an executive report"
 * header. When `opts.logo` (a PNG buffer) is supplied it is embedded on the
 * leading edge of the band; the logo's dark background blends into the navy
 * fill. A null/absent logo simply leaves the text banner (graceful fallback).
 */
export function addBoardBanner(
  ws: Worksheet,
  title: string,
  span: number,
  opts?: { wb?: Workbook; logo?: Buffer | null },
): void {
  ws.mergeCells(1, 1, 1, span);
  ws.mergeCells(2, 1, 2, span);
  ws.mergeCells(3, 1, 3, span);
  // Navy fill across every cell of the band so the colour spans the full width.
  for (let r = 1; r <= 3; r++) {
    for (let c = 1; c <= span; c++) {
      ws.getCell(r, c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: XLSX_NAVY } };
    }
  }
  const brand = ws.getCell(1, 1);
  brand.value = XLSX_BRAND;
  brand.font = { bold: true, size: 11, color: { argb: XLSX_GOLD } };
  brand.alignment = { horizontal: 'right', vertical: 'middle' };

  const t = ws.getCell(2, 1);
  t.value = title;
  t.font = { bold: true, size: 22, color: { argb: 'FFFFFFFF' } };
  t.alignment = { horizontal: 'right', vertical: 'middle' };

  const d = ws.getCell(3, 1);
  d.value = `تاريخ التوليد: ${formatStamp(new Date())}`;
  d.font = { italic: true, size: 10, color: { argb: 'FFCBD5E1' } };
  d.alignment = { horizontal: 'right', vertical: 'middle' };

  ws.getRow(1).height = 22;
  ws.getRow(2).height = 40;
  ws.getRow(3).height = 20;

  if (opts?.wb && opts.logo) {
    const id = opts.wb.addImage({ buffer: opts.logo as unknown as ArrayBuffer, extension: 'png' });
    // Anchor on the leading column of the band (the side opposite the
    // right-aligned brand text); the navy logo backdrop blends into the band.
    ws.addImage(id, { tl: { col: span - 1, row: 0 }, ext: { width: 78, height: 78 } });
  }
}

/**
 * A KPI card grid: each card shows a large bold value over a muted label on a
 * light fill with a box border. `perRow` cards per row, each spanning an equal
 * slice of `span` columns. Cards read as proposal "stat cards", not table rows.
 */
export function addKpiCards(
  ws: Worksheet,
  cards: Array<{ label: string; value: string | number }>,
  opts: { span: number; perRow?: number; bg?: string },
): void {
  if (cards.length === 0) {
    const row = ws.addRow([]);
    ws.mergeCells(row.number, 1, row.number, opts.span);
    const c = ws.getCell(row.number, 1);
    c.value = 'لا توجد بيانات';
    c.font = { italic: true, color: { argb: XLSX_MUTED } };
    c.alignment = { horizontal: 'center', vertical: 'middle' };
    return;
  }
  const perRow = opts.perRow ?? 3;
  const colsPerCard = Math.max(1, Math.floor(opts.span / perRow));
  const bg = opts.bg ?? XLSX_CARD_BG;
  const edge = { style: 'thin' as const, color: { argb: XLSX_CARD_BORDER } };

  for (let i = 0; i < cards.length; i += perRow) {
    const slice = cards.slice(i, i + perRow);
    const valueRow = ws.addRow([]);
    valueRow.height = 30;
    const labelRow = ws.addRow([]);
    labelRow.height = 18;

    slice.forEach((card, j) => {
      const c1 = j * colsPerCard + 1;
      const c2 = c1 + colsPerCard - 1;

      ws.mergeCells(valueRow.number, c1, valueRow.number, c2);
      ws.mergeCells(labelRow.number, c1, labelRow.number, c2);
      for (let c = c1; c <= c2; c++) {
        const vc = ws.getCell(valueRow.number, c);
        vc.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } };
        vc.border = { top: edge, left: edge, right: edge };
        const lc = ws.getCell(labelRow.number, c);
        lc.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } };
        lc.border = { bottom: edge, left: edge, right: edge };
      }

      const v = ws.getCell(valueRow.number, c1);
      v.value = card.value;
      v.font = { bold: true, size: 18, color: { argb: XLSX_NAVY } };
      v.alignment = { horizontal: 'center', vertical: 'middle' };
      if (typeof card.value === 'number') v.numFmt = '#,##0.##';

      const l = ws.getCell(labelRow.number, c1);
      l.value = card.label;
      l.font = { size: 10, color: { argb: XLSX_MUTED } };
      l.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    });

    ws.addRow([]); // gap between card rows
  }
}

/**
 * A clearly-titled chart block: a section title, then the chart image embedded
 * below it with enough reserved rows that following content never overlaps.
 * If `png` is null (render failure), emits a muted "chart unavailable" note —
 * the report still ships its tables.
 */
export function addChartBlock(
  wb: Workbook,
  ws: Worksheet,
  title: string,
  png: Buffer | null,
  opts: { span: number; width: number; height: number },
): void {
  addSectionTitle(ws, title, opts.span);
  if (!png) {
    const row = ws.addRow([]);
    ws.mergeCells(row.number, 1, row.number, opts.span);
    const c = ws.getCell(row.number, 1);
    c.value = 'الرسم البياني غير متاح حالياً';
    c.font = { italic: true, color: { argb: XLSX_MUTED } };
    c.alignment = { horizontal: 'center', vertical: 'middle' };
    return;
  }
  const anchorRow = ws.rowCount; // 0-indexed anchor = first empty row below the title
  const rowsNeeded = Math.ceil(opts.height / 20) + 1;
  for (let i = 0; i < rowsNeeded; i++) ws.addRow([]);
  addChartImage(wb, ws, png, { col: 0, row: anchorRow, width: opts.width, height: opts.height });
}

/**
 * Embed a pre-rendered PNG chart (from xlsx-chart.ts) as a floating image. Pass
 * `null` and it is a no-op — the graceful-fallback path, so a report still emits
 * its tables when chart rendering is unavailable. Position is top-left-anchored
 * at (col,row) (0-indexed) with a pixel extent.
 */
export function addChartImage(
  wb: Workbook,
  ws: Worksheet,
  png: Buffer | null,
  opts: { col?: number; row: number; width: number; height: number },
): void {
  if (!png) return;
  const imageId = wb.addImage({ buffer: png as unknown as ArrayBuffer, extension: 'png' });
  ws.addImage(imageId, {
    tl: { col: opts.col ?? 0, row: opts.row },
    ext: { width: opts.width, height: opts.height },
  });
}

/** A browser-safe `<base>-YYYY-MM-DD.xlsx` download name. Mirrors csvFilename. */
export function xlsxFilename(base: string): string {
  const safe = base.replace(/[^\w.-]+/g, '_');
  const stamp = new Date().toISOString().slice(0, 10);
  return `${safe}-${stamp}.xlsx`;
}

/** Serialize a workbook to a Node Buffer for a StreamableFile response. */
export async function workbookToBuffer(wb: Workbook): Promise<Buffer> {
  const out = await wb.xlsx.writeBuffer();
  return Buffer.from(out as ArrayBuffer);
}
