'use client';

import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';

/**
 * Owner-keyed signed-download button.
 *
 * On click:
 *   1. GET /api-proxy/me/documents?ownerType=…&ownerId=…
 *      → array of CUSTOMER_VISIBLE documents the user owns. The backend's
 *        OwnershipService runs first; a non-owned ownerId returns 404 here
 *        and we surface the friendly empty state.
 *   2. GET /api-proxy/me/documents/{firstDoc.id}/download
 *      → { url, fileName, contentType, expiresIn } where `url` is a
 *        short-lived signed URL (≤5 min) generated by the AWS SDK against
 *        Cloudflare R2. **The URL is never persisted, never logged, and
 *        never written into the rendered DOM** — we hand it to
 *        `window.open(..., '_blank', 'noopener,noreferrer')` and forget.
 *
 * If the owner has no CUSTOMER_VISIBLE document yet (e.g. admin hasn't
 * uploaded the contract PDF), the empty state ("العقد غير متاح بعد") is
 * shown inline. The user can click again later — the next fetch will
 * succeed once the document lands.
 */
type OwnerType = 'CONTRACT' | 'DEPOSIT' | 'MAINTENANCE_REQUEST';

interface Document {
  id: string;
}

interface SignedDownload {
  url: string;
  fileName?: string | null;
  contentType?: string | null;
  expiresIn?: number;
}

export function DocumentDownloadByOwner({
  ownerType,
  ownerId,
  label,
  emptyLabel,
  variant = 'pill',
}: {
  ownerType: OwnerType;
  ownerId: string;
  label: string;
  emptyLabel: string;
  /** `pill` = ContractCard styling, `compact` = sleeker rounded-xl/text-xs
   *  button (PropertyCard), `inline` = DepositCard inline link. */
  variant?: 'pill' | 'compact' | 'inline';
}) {
  const [state, setState] = useState<'idle' | 'loading' | 'empty' | 'error'>('idle');

  async function handleClick() {
    setState('loading');
    try {
      const listRes = await fetch(
        `/api-proxy/me/documents?ownerType=${encodeURIComponent(ownerType)}&ownerId=${encodeURIComponent(ownerId)}`,
        { method: 'GET', credentials: 'include' },
      );
      if (!listRes.ok) {
        setState('error');
        return;
      }
      const docs = (await listRes.json()) as Document[];
      const first = docs[0];
      if (!first) {
        setState('empty');
        return;
      }
      const dlRes = await fetch(
        `/api-proxy/me/documents/${encodeURIComponent(first.id)}/download`,
        { method: 'GET', credentials: 'include' },
      );
      if (!dlRes.ok) {
        setState('error');
        return;
      }
      const signed = (await dlRes.json()) as SignedDownload;
      // The signed URL leaves this function via the new-tab navigation and
      // is dropped from memory. We deliberately do NOT log it.
      window.open(signed.url, '_blank', 'noopener,noreferrer');
      setState('idle');
    } catch {
      setState('error');
    }
  }

  const isInline = variant === 'inline';
  const isCompact = variant === 'compact';

  if (state === 'empty') {
    return (
      <span
        className={
          isInline
            ? 'text-ink-muted/70'
            : isCompact
              ? 'shrink-0 rounded-xl bg-surface-soft px-3.5 py-2 text-xs font-medium text-ink-muted'
              : 'shrink-0 rounded-full bg-surface-soft px-3.5 py-2 text-xs font-medium text-ink-muted'
        }
      >
        {emptyLabel}
      </span>
    );
  }
  if (state === 'error') {
    return (
      <button
        type="button"
        onClick={handleClick}
        className={
          isInline
            ? 'inline-flex items-center gap-1.5 font-medium text-red-600 hover:text-red-500'
            : isCompact
              ? 'inline-flex shrink-0 items-center gap-1.5 rounded-xl border border-red-300 bg-surface px-3.5 py-2 text-xs font-medium text-red-600 hover:border-red-400'
              : 'inline-flex shrink-0 items-center gap-2 rounded-full border border-red-300 bg-surface px-4 py-2 text-sm font-medium text-red-600 hover:border-red-400'
        }
      >
        تعذر الفتح — حاول مرة أخرى
      </button>
    );
  }

  const baseClass = isInline
    ? 'inline-flex items-center gap-1.5 font-medium text-gold-600 transition-colors hover:text-gold-500 disabled:cursor-progress disabled:opacity-70'
    : isCompact
      ? 'inline-flex shrink-0 items-center gap-1.5 rounded-xl border border-hairline/60 bg-surface-soft px-3.5 py-2 text-xs font-medium text-ink-muted transition-colors hover:border-hairline hover:text-ink-strong disabled:cursor-progress disabled:opacity-70'
      : 'inline-flex shrink-0 items-center gap-2 rounded-full border border-hairline bg-surface px-4 py-2 text-sm font-medium text-ink-strong transition-colors hover:border-gold-300 hover:text-gold-600 disabled:cursor-progress disabled:opacity-70';

  const iconSize = isInline ? 'h-3.5 w-3.5' : 'h-4 w-4';

  return (
    <button type="button" onClick={handleClick} disabled={state === 'loading'} className={baseClass}>
      {state === 'loading' ? (
        <Loader2 className={`${iconSize} animate-spin`} aria-hidden />
      ) : (
        <Download className={iconSize} aria-hidden />
      )}
      {state === 'loading' ? 'جارٍ التحضير...' : label}
    </button>
  );
}
