// TODO(Phase 5 / Firebase): Replace this stub with the real file generated by
// `flutterfire configure`. See docs/mobile-firebase-setup.md for instructions.
//
// Until replaced, Firebase.initializeApp() in bootstrap.dart catches the thrown
// UnsupportedError and continues with Firebase disabled (push = off, IN_APP ok).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'Firebase is not configured for this app.\n'
          'Run `flutterfire configure` inside apps/mobile/mobile_staff/ '
          'to generate the real firebase_options.dart.\n'
          'See docs/mobile-firebase-setup.md for step-by-step instructions.',
        );
      default:
        throw UnsupportedError('Firebase push is not supported on this platform.');
    }
  }
}
