import { type Cell, Workbook, type Worksheet } from 'exceljs';
import {
  addBoardBanner,
  addChartBlock,
  addFooter,
  addKpiCards,
  addReportTitle,
  addSectionTitle,
  addTable,
  amountFormat,
  createReportWorkbook,
  currencyNote,
  excelLocalDate,
  formatMoneyColumns,
  formatStamp,
  setupBoardSheet,
  styleHeaderCell,
  styleTotalsRow,
  workbookToBuffer,
  writeAmountCell,
  writeDateCell,
  writeTextCell,
  xlsxFilename,
  XLSX_BRAND,
} from '../xlsx';

/**
 * P15.2 — shared XLSX foundation. Verifies the reusable helpers produce a valid,
 * RTL, styled workbook so every export across the platform inherits the same
 * professional theme.
 */
describe('shared XLSX foundation', () => {
  it('serializes a real .xlsx (ZIP "PK" magic) that round-trips through exceljs', async () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('ورقة');
    addTable(ws, ['الاسم', 'العدد'], [['ألف', 3], ['باء', 7]], [20, 12]);

    const buf = await workbookToBuffer(wb);
    expect(buf.subarray(0, 4)).toEqual(Buffer.from([0x50, 0x4b, 0x03, 0x04]));

    const reopened = new Workbook();
    await reopened.xlsx.load(buf as unknown as ArrayBuffer);
    expect(reopened.getWorksheet('ورقة')).toBeDefined();
    expect(wb.creator).toBe(XLSX_BRAND);
  });

  it('addTable sets RTL view, styled header, and an empty-state row when no data', () => {
    const wb = new Workbook();
    const filled = wb.addWorksheet('filled');
    addTable(filled, ['ع', 'ق'], [['x', 1]], [10, 10]);
    expect(filled.views[0]).toMatchObject({ rightToLeft: true, state: 'frozen' });
    // header row 1, cell fill is the navy header
    expect(filled.getRow(1).getCell(1).fill).toMatchObject({ type: 'pattern', pattern: 'solid' });

    const empty = wb.addWorksheet('empty');
    addTable(empty, ['ع', 'ق'], [], [10, 10]);
    // header (row 1) + the merged "لا توجد بيانات" placeholder (row 2)
    expect(empty.getRow(2).getCell(1).value).toBe('لا توجد بيانات');
  });

  it('addReportTitle writes a navy title + a generated-on stamp; addFooter brands it', () => {
    const wb = new Workbook();
    const ws = wb.addWorksheet('s');
    ws.columns = [{ width: 20 }, { width: 20 }];
    addReportTitle(ws, 'عنوان التقرير');
    addFooter(ws);

    expect(ws.getCell('A1').value).toBe('عنوان التقرير');
    expect(String(ws.getCell('A2').value)).toContain('تاريخ التوليد:');
    const flat: string[] = [];
    ws.eachRow((r) => r.eachCell((c) => flat.push(String(c.value ?? ''))));
    expect(flat.join(' ')).toContain(`Generated by ${XLSX_BRAND}`);
  });

  it('board layout: setupBoardSheet hides gridlines + RTL; banner + KPI cards render', async () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('الملخص');
    setupBoardSheet(ws, { widths: [16, 16, 16, 16, 16, 16], landscape: true });
    addBoardBanner(ws, 'تقرير لوحة التحكم', 6);
    addSectionTitle(ws, 'الملخص التنفيذي', 6);
    addKpiCards(ws, [
      { label: 'المشاريع', value: 4 },
      { label: 'الوحدات', value: 100 },
      { label: 'الفرص', value: 8 },
    ], { span: 6, perRow: 3 });

    // RTL + gridlines hidden survive a load round-trip.
    const buf = await workbookToBuffer(wb);
    const re = new Workbook();
    await re.xlsx.load(buf as unknown as ArrayBuffer);
    const view = re.getWorksheet('الملخص')!.views[0] as { rightToLeft?: boolean; showGridLines?: boolean };
    expect(view.rightToLeft).toBe(true);
    expect(view.showGridLines).toBe(false);

    // Banner title present; a KPI value sits directly above its label.
    const cover = re.getWorksheet('الملخص')!;
    expect(cover.getCell('A2').value).toBe('تقرير لوحة التحكم');
    let projects: number | undefined;
    cover.eachRow((row, rn) =>
      row.eachCell((cell, cn) => {
        if (String(cell.value) === 'المشاريع') projects = Number(cover.getCell(rn - 1, cn).value);
      }),
    );
    expect(projects).toBe(4);
  });

  it('addChartBlock with a null chart is a no-op note (graceful) — no throw, no image', () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('s');
    setupBoardSheet(ws, { widths: [16, 16, 16, 16, 16, 16] });
    expect(() => addChartBlock(wb, ws, 'الرسم', null, { span: 6, width: 600, height: 300 })).not.toThrow();
    expect(ws.getImages().length).toBe(0);
  });

  it('style helpers + formatStamp/xlsxFilename behave', () => {
    const wb = new Workbook();
    const ws = wb.addWorksheet('s');
    const header = ws.addRow(['h']);
    styleHeaderCell(header.getCell(1));
    expect(header.getCell(1).font).toMatchObject({ bold: true });

    const totals = ws.addRow(['الإجمالي', 10]);
    styleTotalsRow(totals);
    expect(totals.getCell(1).font).toMatchObject({ bold: true });

    expect(formatStamp(new Date('2026-05-31T07:09:00'))).toMatch(/^2026-05-31 \d{2}:09$/);
    expect(xlsxFilename('my report!!')).toMatch(/^my_report_-\d{4}-\d{2}-\d{2}\.xlsx$/);
  });
});

// ── Cell-type safety helpers ──────────────────────────────────────────────────

/**
 * Writes one cell via `fn`, serializes to XLSX buffer, reloads via a fresh
 * Workbook, and returns the reloaded cell. This is the only way to prove the
 * value survived ExcelJS serialization — in-memory state is not sufficient
 * because ExcelJS normalizes on write.
 */
async function roundTripCell(
  fn: (ws: Worksheet) => void,
): Promise<(row: number, col: number) => Cell> {
  const wb = new Workbook();
  const ws = wb.addWorksheet('data');
  fn(ws);
  const buf = await workbookToBuffer(wb);
  const wb2 = new Workbook();
  await wb2.xlsx.load(buf as unknown as ArrayBuffer);
  return (r: number, c: number) => wb2.getWorksheet('data')!.getRow(r).getCell(c);
}

describe('cell-type safety helpers — round-trip through xlsx serialization', () => {
  it('writeTextCell: phone with leading zero survives unchanged', async () => {
    const get = await roundTripCell((ws) =>
      writeTextCell(ws.getRow(1).getCell(1), '01062800394'),
    );
    expect(get(1, 1).value).toBe('01062800394');
    expect(get(1, 1).numFmt).toBe('@');
  });

  it('writeTextCell: 14-digit national ID is not rounded', async () => {
    const get = await roundTripCell((ws) =>
      writeTextCell(ws.getRow(1).getCell(1), '29901011234567'),
    );
    // If stored as a number, Excel rounds at 15 sig-digits → last digit zeroed.
    expect(get(1, 1).value).toBe('29901011234567');
    expect(get(1, 1).numFmt).toBe('@');
  });

  it('writeTextCell: _Ref resembling scientific notation is preserved as-is', async () => {
    // "3e7f9c12" matches [digit]e[hex] — auto-parser bait without text typing.
    const get = await roundTripCell((ws) =>
      writeTextCell(ws.getRow(1).getCell(1), '3e7f9c12'),
    );
    expect(get(1, 1).value).toBe('3e7f9c12');
    expect(get(1, 1).numFmt).toBe('@');
  });

  it('writeTextCell: number argument is coerced to string (no silent leading-zero drop)', async () => {
    // Callers should always pass strings, but if they pass a number it must not
    // silently become the wrong type.
    const get = await roundTripCell((ws) =>
      writeTextCell(ws.getRow(1).getCell(1), 42 as unknown as string),
    );
    expect(typeof get(1, 1).value).toBe('string');
    expect(get(1, 1).value).toBe('42');
  });

  it('writeTextCell: null writes empty string (import contract: empty = no value)', async () => {
    const get = await roundTripCell((ws) =>
      writeTextCell(ws.getRow(1).getCell(1), null),
    );
    // null → '' so the cell is always present in the serialized file.
    // ExcelJS may return '' or null after round-trip for an empty text cell;
    // both satisfy the contract (cell exists, no data loss risk).
    expect(get(1, 1).value == null || get(1, 1).value === '').toBe(true);
  });

  it('writeDateCell: Date value round-trips with YYYY-MM-DD numFmt (locale-independent)', async () => {
    const get = await roundTripCell((ws) =>
      writeDateCell(ws.getRow(1).getCell(1), new Date('2026-09-24T12:00:00Z')),
    );
    expect(get(1, 1).value).toBeInstanceOf(Date);
    expect(get(1, 1).numFmt).toBe('YYYY-MM-DD');
  });

  it('writeDateCell: ISO string is accepted and stored as a Date', async () => {
    const get = await roundTripCell((ws) =>
      writeDateCell(ws.getRow(1).getCell(1), '2026-01-15'),
    );
    expect(get(1, 1).value).toBeInstanceOf(Date);
  });

  it('writeDateCell: null writes null without throwing', async () => {
    const get = await roundTripCell((ws) =>
      writeDateCell(ws.getRow(1).getCell(1), null),
    );
    expect(get(1, 1).value).toBeNull();
  });

  it('writeAmountCell: number stored with #,##0.00 format and correct value', async () => {
    const get = await roundTripCell((ws) =>
      writeAmountCell(ws.getRow(1).getCell(1), 1_234_567.89),
    );
    expect(typeof get(1, 1).value).toBe('number');
    expect(get(1, 1).numFmt).toBe('#,##0.00');
    expect(get(1, 1).value as number).toBeCloseTo(1_234_567.89);
  });

  it('writeAmountCell: Prisma Decimal-like object (toString) is accepted', async () => {
    const decimal = { toString: () => '99999.50' };
    const get = await roundTripCell((ws) =>
      writeAmountCell(ws.getRow(1).getCell(1), decimal),
    );
    expect(typeof get(1, 1).value).toBe('number');
    expect(get(1, 1).value as number).toBeCloseTo(99999.5);
  });

  it('writeAmountCell: null writes null without throwing', async () => {
    const get = await roundTripCell((ws) =>
      writeAmountCell(ws.getRow(1).getCell(1), null),
    );
    expect(get(1, 1).value).toBeNull();
  });
});

/**
 * Report amounts carry the company currency: once in every workbook header,
 * and as a number-format suffix on money cells (the value stays a number).
 */
describe('company currency in workbooks', () => {
  it('amountFormat / currencyNote name the currency', () => {
    expect(amountFormat()).toBe('#,##0.00');
    expect(amountFormat('EGP')).toBe('#,##0.00 "ج.م"');
    expect(amountFormat('SAR', '0.##')).toBe('#,##0.## "ر.س"');
    expect(currencyNote('sar')).toBe('العملة: ر.س (SAR)');
    expect(currencyNote('nope')).toBe('العملة: ج.م (EGP)');
  });

  it('report title, board banner and money KPI cards show the currency', () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('t');
    addReportTitle(ws, 'تقرير', 3, 'SAR');
    expect(String(ws.getCell(2, 1).value)).toContain('العملة: ر.س (SAR)');

    const board = wb.addWorksheet('b');
    addBoardBanner(board, 'تقرير', 6, { currency: 'AED' });
    expect(String(board.getCell(3, 1).value)).toContain('(AED)');

    addKpiCards(board, [
      { label: 'العقود', value: 3 },
      { label: 'الإجمالي', value: 1250, currency: 'AED' },
    ], { span: 6, perRow: 2 });
    const valueRow = board.rowCount - 2; // value row, label row, gap row
    expect(board.getCell(valueRow, 1).numFmt).toBe('#,##0.##');
    expect(board.getCell(valueRow, 4).numFmt).toBe('#,##0.## "د.إ"');
  });

  it('money cells and columns keep a numeric value with the symbol format', () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('m');
    writeAmountCell(ws.getCell(1, 1), 99.5, 'EGP');
    expect(ws.getCell(1, 1).value).toBe(99.5);
    expect(ws.getCell(1, 1).numFmt).toBe('#,##0.00 "ج.م"');
    formatMoneyColumns(ws, [2, 3], 'KWD');
    expect(ws.getColumn(3).numFmt).toBe('#,##0.## "د.ك"');
  });
});

describe('times in the company time zone', () => {
  // 09:35 UTC on 2026-10-09 is 12:35 in Cairo (EEST, UTC+3).
  const at = new Date('2026-10-09T09:35:45.244Z');

  it('formats a stamp in the given zone', () => {
    expect(formatStamp(at, 'Africa/Cairo')).toBe('2026-10-09 12:35');
    expect(formatStamp(at, 'UTC')).toBe('2026-10-09 09:35');
  });

  it('crosses midnight with the zone', () => {
    expect(formatStamp(new Date('2026-10-09T22:30:00Z'), 'Africa/Cairo')).toBe('2026-10-10 01:30');
  });

  it('shifts a cell date so Excel shows the local wall clock', () => {
    expect(excelLocalDate(at, 'Africa/Cairo').toISOString()).toBe('2026-10-09T12:35:45.000Z');
  });
});
