import { Workbook } from 'exceljs';
import {
  addBoardBanner,
  addChartBlock,
  addFooter,
  addKpiCards,
  addReportTitle,
  addSectionTitle,
  addTable,
  createReportWorkbook,
  formatStamp,
  setupBoardSheet,
  styleHeaderCell,
  styleTotalsRow,
  workbookToBuffer,
  xlsxFilename,
  XLSX_BRAND,
} from '../xlsx';

/**
 * P15.2 — shared XLSX foundation. Verifies the reusable helpers produce a valid,
 * RTL, styled workbook so every export across the platform inherits the same
 * professional theme.
 */
describe('shared XLSX foundation', () => {
  it('serializes a real .xlsx (ZIP "PK" magic) that round-trips through exceljs', async () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('ورقة');
    addTable(ws, ['الاسم', 'العدد'], [['ألف', 3], ['باء', 7]], [20, 12]);

    const buf = await workbookToBuffer(wb);
    expect(buf.subarray(0, 4)).toEqual(Buffer.from([0x50, 0x4b, 0x03, 0x04]));

    const reopened = new Workbook();
    await reopened.xlsx.load(buf as unknown as ArrayBuffer);
    expect(reopened.getWorksheet('ورقة')).toBeDefined();
    expect(wb.creator).toBe(XLSX_BRAND);
  });

  it('addTable sets RTL view, styled header, and an empty-state row when no data', () => {
    const wb = new Workbook();
    const filled = wb.addWorksheet('filled');
    addTable(filled, ['ع', 'ق'], [['x', 1]], [10, 10]);
    expect(filled.views[0]).toMatchObject({ rightToLeft: true, state: 'frozen' });
    // header row 1, cell fill is the navy header
    expect(filled.getRow(1).getCell(1).fill).toMatchObject({ type: 'pattern', pattern: 'solid' });

    const empty = wb.addWorksheet('empty');
    addTable(empty, ['ع', 'ق'], [], [10, 10]);
    // header (row 1) + the merged "لا توجد بيانات" placeholder (row 2)
    expect(empty.getRow(2).getCell(1).value).toBe('لا توجد بيانات');
  });

  it('addReportTitle writes a navy title + a generated-on stamp; addFooter brands it', () => {
    const wb = new Workbook();
    const ws = wb.addWorksheet('s');
    ws.columns = [{ width: 20 }, { width: 20 }];
    addReportTitle(ws, 'عنوان التقرير');
    addFooter(ws);

    expect(ws.getCell('A1').value).toBe('عنوان التقرير');
    expect(String(ws.getCell('A2').value)).toContain('تاريخ التوليد:');
    const flat: string[] = [];
    ws.eachRow((r) => r.eachCell((c) => flat.push(String(c.value ?? ''))));
    expect(flat.join(' ')).toContain(`Generated by ${XLSX_BRAND}`);
  });

  it('board layout: setupBoardSheet hides gridlines + RTL; banner + KPI cards render', async () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('الملخص');
    setupBoardSheet(ws, { widths: [16, 16, 16, 16, 16, 16], landscape: true });
    addBoardBanner(ws, 'تقرير لوحة التحكم', 6);
    addSectionTitle(ws, 'الملخص التنفيذي', 6);
    addKpiCards(ws, [
      { label: 'المشاريع', value: 4 },
      { label: 'الوحدات', value: 100 },
      { label: 'الفرص', value: 8 },
    ], { span: 6, perRow: 3 });

    // RTL + gridlines hidden survive a load round-trip.
    const buf = await workbookToBuffer(wb);
    const re = new Workbook();
    await re.xlsx.load(buf as unknown as ArrayBuffer);
    const view = re.getWorksheet('الملخص')!.views[0] as { rightToLeft?: boolean; showGridLines?: boolean };
    expect(view.rightToLeft).toBe(true);
    expect(view.showGridLines).toBe(false);

    // Banner title present; a KPI value sits directly above its label.
    const cover = re.getWorksheet('الملخص')!;
    expect(cover.getCell('A2').value).toBe('تقرير لوحة التحكم');
    let projects: number | undefined;
    cover.eachRow((row, rn) =>
      row.eachCell((cell, cn) => {
        if (String(cell.value) === 'المشاريع') projects = Number(cover.getCell(rn - 1, cn).value);
      }),
    );
    expect(projects).toBe(4);
  });

  it('addChartBlock with a null chart is a no-op note (graceful) — no throw, no image', () => {
    const wb = createReportWorkbook();
    const ws = wb.addWorksheet('s');
    setupBoardSheet(ws, { widths: [16, 16, 16, 16, 16, 16] });
    expect(() => addChartBlock(wb, ws, 'الرسم', null, { span: 6, width: 600, height: 300 })).not.toThrow();
    expect(ws.getImages().length).toBe(0);
  });

  it('style helpers + formatStamp/xlsxFilename behave', () => {
    const wb = new Workbook();
    const ws = wb.addWorksheet('s');
    const header = ws.addRow(['h']);
    styleHeaderCell(header.getCell(1));
    expect(header.getCell(1).font).toMatchObject({ bold: true });

    const totals = ws.addRow(['الإجمالي', 10]);
    styleTotalsRow(totals);
    expect(totals.getCell(1).font).toMatchObject({ bold: true });

    expect(formatStamp(new Date('2026-05-31T07:09:00'))).toMatch(/^2026-05-31 \d{2}:09$/);
    expect(xlsxFilename('my report!!')).toMatch(/^my_report_-\d{4}-\d{2}-\d{2}\.xlsx$/);
  });
});
